site_name: Autosuggest Docs
nav:
    - What is Autosuggest: index.md
    - Authentication: authentication.md
    - Uploading Training Data: data-upload.md
    - Models:
      - Electronic Invoice Line: models/einvoice-model.md
      - Bank: models/bank.md
      - Scanned Invoice: models/scanned-invoice.md
      - Supplier Name: models/supplier-name.md
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'teal'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition
