site_name: Autosuggest Docs
pages:
    - What is Autosuggest: index.md
    - Uploading Training Data: data_upload.md
    - Models:
      - Electronic Invoice Line: einvoice_model.md
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'teal'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition
